thewatermanagement/applications/blog/urls.py
from django.urls import include, path
from . import views

app_name = 'blog_app'

urlpatterns = [
    path(
        '',
        views.BlogListView.as_view(),
        name='list_blog'
    ),
    path(
        'detail_post/<pk>/',
        views.PostDetailView.as_view(),
        name='detail_post'
    )
]

thewatermanagement/applications/home/urls.py
from django.urls import include, path
from . import views

app_name = 'home_app'

urlpatterns = [
    path('',
        views.HomePageView.as_view(),
        name='home',
    ),
]

thewatermanagement/thewatermanagement/urls.py
from django.contrib import admin
from django.urls import path
#INCLUIDOS
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path('', include('applications.home.urls')),
    re_path('blog/', include('applications.blog.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thewatermanagement/applications/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title_post = models.CharField('Título', max_length=400, null=True,blank=True)
    text_post = models.TextField('Texto', max_length=1000, null=True,blank=True)
    link_post = models.CharField('Enlace', max_length=500, null=True, blank=True)
    date_post = models.DateTimeField('Fecha',null=True, blank=True)
    author_post = models.CharField('Autor', max_length=20,null=True, blank=True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural= 'Post'
        ordering = ['date_post']

    def __str__(self):
        return self.link_post

thewatermanagement/applications/home/models.py
from django.db import models

# Create your models here.

thewatermanagement/applications/blog/views.py
from django.shortcuts import render
from django.utils import timezone
from applications.blog.models import Post
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy, reverse

# Create your views here.
class BlogListView(ListView):
    template_name = 'blog/blog.html'
    def get_queryset(self):
        object_list = Post.objects.all()
        return object_list

class PostDetailView(DetailView):
    model = Post
    template_name = "blog/detail_post.html"

thewatermanagement/applications/home/views.py
from django.shortcuts import render
#AÑADIDOS
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    TemplateView,
    ListView
)


# Create your views here.
class HomePageView(TemplateView):
    template_name = "home/index.html"

thewatermanagement/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    {% block title %}
    {% endblock %}
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">



    {% block head %}
    {% endblock %}

  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
    <a class="navbar-brand" href="#">
        <img height="45px" src="{% static 'img/logo/color-logo.png' %}">
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home_app:home' %}">Inicio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Descargar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog_app:list_blog' %}">Novedades</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" >Ayuda</a>
      </li>
    </ul>
    
      <a><button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Iniciar sesión</button></a>
    
  </div>
</nav>

<main role="main" class="container-fluid"></main>


    
    {% block header %}
    {% endblock %}
      
    {% block slider %}
    {% endblock %}

    {% block content %}
    {% endblock %}




</main>






<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>

thewatermanagement/templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Blog - The Water Management</title>
{% endblock %}

{% block header %}

{% endblock %}

{% block slider %}

  {% endblock %}


{% block content %}

<div class="container fluid">
  <div class="row align-items-center pt-3">
        <div class="col-md text-center">
            <h1 class="h3 text-canter"><b>Novedades</b></h1>
        </div>
    </div>
</div>

{% for post in object_list %}
<div class="container fluid">
    <div class="row align-items-center pt-5 pb-5">
        <div class="col-md">
            <a href="{% url 'blog_app:detail_post' post.id %}"><h1 class="h1" style="text-decoration: none; color:#00899b"><b>{{ post.title_post }}</b></h1></a>
            <h5 class="h5 text-secondary ml-5">Autor: {{ post.author_post }}</h4>
            <p class="text-justify">{{ post.text_post }}</p>
            <iframe width="100%" height="721" src="{{ post.link_post }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 
        </div>
    </div>
</div>
{% endfor %}


   
<div class="bg-light">
    <div class="container">
        
        <div class="row align-items-center pt-5 pb-5">
            <div class="col-md text-center">
                <a href="#"><img class="pl-1 pr-1" style="height:50px;" src="{% static 'img/facebook.png' %}"></a>
                <a href="#"><img class="pl-1 pr-1" style="height:50px;" src="{% static 'img/linkedin.png' %}"></a>
                <a href="https://www.youtube.com/channel/UC3ifiKYzN-485sKeadh1w-g"><img class="pl-1 pr-1" style="height:50px;" src="{% static 'img/youtube.png' %}"></a>
                <h3 class="pt-3">TheWaterManagement</h3>
            </div>
        </div>
        
    </div>
</div>

    <div class="container">
        <div class="row align-items-center pt-5">
            <div class="col-md text-center">
                <img style="height:50px;" src="{% static 'img/logo/color-logo.png' %}">
            </div>
        </div>    
        <div class="row align-items-center pt-2 pb-5">
            <div class="col-md text-center">
                <h3>Información</h3><br>
                <a class="text-dark" href="#">Cookies</a><br>
                <a class="text-dark" href="#">Privacidad</a><br>
                <a class="text-dark" href="#">Términos y condiciones</a><br>
                
            </div>
        </div>
    </div>

<div class="bg-secondary">    
    <div class="container"> 
        <div class="row align-items-center pt-5 pb-5">
            <div class="col-md text-center">
                <p>Copyright (c) 2019-2020 TheWaterManagement by <a target="_blank" href="https://www.linkedin.com/in/inakiretegi/">Iñaki Retegi</a></p>                
            </div>
        </div>
        
    </div>
</div>




{% endblock %}

thewatermanagement/templates/blog/detail_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Blog - The Water Management</title>
{% endblock %}

{% block header %}

{% endblock %}

{% block slider %}

  {% endblock %}


{% block content %}

<div class="container fluid">
  <div class="row align-items-center pt-3">
        <div class="col-md text-center">
            <h1 class="h3 text-canter"><b>Detalles POST</b></h1>
        </div>
    </div>
</div>


<div class="container fluid">
    <div class="row align-items-center pt-5 pb-5">
        <div class="col-md">
            <a href=""><h1 class="h1" style="text-decoration: none; color:#00899b"><b>{{ post.title_post }}</b></h1></a>
            <h5 class="h5 text-secondary ml-5">Autor: {{ post.author_post }}</h4>
            <p class="text-justify">{{ post.text_post }}</p>
            <iframe width="100%" height="721" src="{{ post.link_post }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 
        </div>
        
    </div>
    <div class="row align-items-center">
        <div class="col-12">
        <form>
            <div class="form-group">
              <label for="exampleInputEmail1">Comentario</label>
              <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="">
            </div>
            
            <button style="background-color:#00899b" type="submit" class="btn btn-primary">Enviar</button>
        </form>
        </div>
    </div>
</div>



   
<div class="bg-light">
    <div class="container">
        
        <div class="row align-items-center pt-5 pb-5">
            <div class="col-md text-center">
                <a href="#"><img class="pl-1 pr-1" style="height:50px;" src="{% static 'img/facebook.png' %}"></a>
                <a href="#"><img class="pl-1 pr-1" style="height:50px;" src="{% static 'img/linkedin.png' %}"></a>
                <a href="https://www.youtube.com/channel/UC3ifiKYzN-485sKeadh1w-g"><img class="pl-1 pr-1" style="height:50px;" src="{% static 'img/youtube.png' %}"></a>
                <h3 class="pt-3">TheWaterManagement</h3>
            </div>
        </div>
        
    </div>
</div>

    <div class="container">
        <div class="row align-items-center pt-5">
            <div class="col-md text-center">
                <img style="height:50px;" src="{% static 'img/logo/color-logo.png' %}">
            </div>
        </div>    
        <div class="row align-items-center pt-2 pb-5">
            <div class="col-md text-center">
                <h3>Información</h3><br>
                <a class="text-dark" href="#">Cookies</a><br>
                <a class="text-dark" href="#">Privacidad</a><br>
                <a class="text-dark" href="#">Términos y condiciones</a><br>
                
            </div>
        </div>
    </div>

<div class="bg-secondary">    
    <div class="container"> 
        <div class="row align-items-center pt-5 pb-5">
            <div class="col-md text-center">
                <p>Copyright (c) 2019-2020 TheWaterManagement by <a target="_blank" href="https://www.linkedin.com/in/inakiretegi/">Iñaki Retegi</a></p>                
            </div>
        </div>
        
    </div>
</div>




{% endblock %}

thewatermanagement/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Home - The Water Management</title>
{% endblock %}

{% block header %}

{% endblock %}

{% block slider %}

  {% endblock %}


{% block content %}




<div class="container fluid">
    <img class="row pt-5 w-100" src="{% static 'img/thewatermanagement-header.jpg' %}">
    <div class="row align-items-center pt-5 pb-5">
        <div class="col-md">
            <h1 class="h3"><b>TheWaterManagement</b></h1><h1 class="h4">Software libre para el mantenimiento y la gestion del agua</h1>
            <p class="text-justify">TheWaterManagement es un programa de mantenimiento y gestión del agua que puede instalar en su PC o en su hosting. Con él podrá gestionar el día a día de la actividad relacionada con el agua: estaciones de agua, instalaciones, dispositivos, mantenimiento correctivo, mantenimiento preventivo, estadísticas, etc. Así que, ya sea un ayuntamiento o una empresa privada, no lo dude y pruebe TheWaterManagement totalmente gratis. No le llevará más de unos minutos descubrir que tenemos todo lo que necesita para su gestión.</p>
            <p><a target="_blank" href="https://github.com/retegi/aguas"><button class="btn btn-success">Descargar</button></a></p>
        </div>
    </div>
</div>

<div class="bg-light">
    <div class="container">
        <div class="row align-items-center pt-5 pb-5 bg-light">
            
            <div class="col-md text-center pl-5 pr-5">
                <i class="fa fa-thumbs-up fa-2x">
                    <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16v-1c.563 0 .901-.272 1.066-.56a.865.865 0 0 0 .121-.416c0-.12-.035-.165-.04-.17l-.354-.354.353-.354c.202-.201.407-.511.505-.804.104-.312.043-.441-.005-.488l-.353-.354.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315L12.793 9l.353-.354c.353-.352.373-.713.267-1.02-.122-.35-.396-.593-.571-.652-.653-.217-1.447-.224-2.11-.164a8.907 8.907 0 0 0-1.094.171l-.014.003-.003.001a.5.5 0 0 1-.595-.643 8.34 8.34 0 0 0 .145-4.726c-.03-.111-.128-.215-.288-.255l-.262-.065c-.306-.077-.642.156-.667.518-.075 1.082-.239 2.15-.482 2.85-.174.502-.603 1.268-1.238 1.977-.637.712-1.519 1.41-2.614 1.708-.394.108-.62.396-.62.65v4.002c0 .26.22.515.553.55 1.293.137 1.936.53 2.491.868l.04.025c.27.164.495.296.776.393.277.095.63.163 1.14.163h3.5v1H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                    </svg>
                </i>
                <h3>Sencillo e intuitivo</h3>
                <p>Ventanas de control sencillas con las opciones imprescindibles. Invertimos muchísimo tiempo en diseñar la usabilidad.</p>
            </div>
 
            <div class="col-md text-center pl-5 pr-5">
                <i class="fa fa-thumbs-up fa-2x"></i>
                    <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-unlock" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M9.655 8H2.333c-.264 0-.398.068-.471.121a.73.73 0 0 0-.224.296 1.626 1.626 0 0 0-.138.59V14c0 .342.076.531.14.635.064.106.151.18.256.237a1.122 1.122 0 0 0 .436.127l.013.001h7.322c.264 0 .398-.068.471-.121a.73.73 0 0 0 .224-.296 1.627 1.627 0 0 0 .138-.59V9c0-.342-.076-.531-.14-.635a.658.658 0 0 0-.255-.237A1.122 1.122 0 0 0 9.655 8zm.012-1H2.333C.5 7 .5 9 .5 9v5c0 2 1.833 2 1.833 2h7.334c1.833 0 1.833-2 1.833-2V9c0-2-1.833-2-1.833-2zM8.5 4a3.5 3.5 0 1 1 7 0v3h-1V4a2.5 2.5 0 0 0-5 0v3h-1V4z"/>
                    </svg>
                </i>
                <h3>Software libre</h3>
                <p>Escrito en Python, con licencia LGPL y el código en github. No se quedará atrapado en la plataforma de otro, ni le costará encontrar programadores que se lo adapten.</p>
            </div>

            <div class="col-md text-center pl-5 pr-5">
                <i class="fa fa-thumbs-up fa-2x"></i>
                    <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-arrow-clockwise" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z"/>
                        <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z"/>
                    </svg>
                </i>
                <h3>Actualizaciones constantes</h3>
                <p>El mundo cambia muy rápido y no espera a nadie. Lanzamos actualizaciones constantes con nuevas funciones, correcciones.</p>
            </div>
        </div>
    </div>
</div>
<div>
    <div class="container">
        <div class="row align-items-center pt-5 pb-5">
            <div class="col-md">
                <img class="w-100" src="{% static 'img/thewatermanagement-responsive.png' %}">
            </div>
            <div class="col-md text-center">
                <h3>PC, Tablet y Smartphone</h3>
                <p class="text-canter">Software adaptado a diferentes dispositivos: PC, Laptop, Table y Smartphone. Pueden trabajar de forma simultanea.</p>
            </div>
        </div>

        <div class="row align-items-center pt-5 pb-5">
            <div class="col-md text-center">
                <h3>Roles de usuario</h3>
                <p class="">Gestión de accesos y privilegios mediante grupos de usuarios, y usuarios individuales. Esto permitira dar acceso a cada usuario a las funciones necesarias para mayor facilidad de gestión y para garantizar la seguridad y la confidencialidad de la información.</p>
            </div>
            <div class="col-md">
                <img class="w-100" src="{% static 'img/thewatermanagement-people.png' %}">
            </div>
        </div>
    </div>
<div class="bg-light">
    <div class="container">
        
        <div class="row align-items-center pt-5 pb-5">
            <div class="col-md text-center">
                <a href="#"><img class="pl-1 pr-1" style="height:50px;" src="{% static 'img/facebook.png' %}"></a>
                <a href="#"><img class="pl-1 pr-1" style="height:50px;" src="{% static 'img/linkedin.png' %}"></a>
                <a href="https://www.youtube.com/channel/UC3ifiKYzN-485sKeadh1w-g"><img class="pl-1 pr-1" style="height:50px;" src="{% static 'img/youtube.png' %}"></a>
                <h3 class="pt-3">TheWaterManagement</h3>
            </div>
        </div>
        
    </div>
</div>

    <div class="container">
        <div class="row align-items-center pt-5">
            <div class="col-md text-center">
                <img style="height:50px;" src="{% static 'img/logo/color-logo.png' %}">
            </div>
        </div>    
        <div class="row align-items-center pt-2 pb-5">
            <div class="col-md text-center">
                <h3>Información</h3><br>
                <a class="text-dark" href="#">Cookies</a><br>
                <a class="text-dark" href="#">Privacidad</a><br>
                <a class="text-dark" href="#">Términos y condiciones</a><br>
                
            </div>
        </div>
    </div>

<div class="bg-secondary">    
    <div class="container"> 
        <div class="row align-items-center pt-5 pb-5">
            <div class="col-md text-center">
                <p>Copyright (c) 2019-2020 TheWaterManagement by <a target="_blank" href="https://www.linkedin.com/in/inakiretegi/">Iñaki Retegi</a></p>                
            </div>
        </div>
        
    </div>
</div>
</div>



{% endblock %}